#macro FRAME_RATE 120
#macro MAX_CAST_TIME 6
#macro ACTION_TIME_REFRESH 0.1
#macro ACTION_TIMER 1000000*ACTION_TIME_REFRESH


#macro STATIC_VALUE "STATIC_VALUE"
#macro PLAYER_DEFINED "PLAYER_DEFINED"
#macro EQUIPMENT "EQUIPMENT"
#macro SPELL "SPELL"
#macro WEAPON "WEAPON"
#macro MELEE "MELEE"
#macro DISTANCE "DISTANCE"
#macro ITEM "ITEM"
#macro BAG "BAG"
#macro ACTION_KEY "ACTION_KEY"
#macro INSTANT "INSTANT"

//Rangos
#macro PERSONAL "PERSONAL"
#macro TOUCH "TOUCH"
#macro CLOSE_RANGE "CLOSE_RANGE"
#macro MEDIUM_RANGE "MEDIUM_RANGE"
#macro LONG_RANGE "LONG_RANGE"
#macro UNLIMITED_RANGE "UNLIMITED_RANGE"


#macro FULL "FULL"
#macro HALF "HALF"
#macro NEGATE "NEGATE"

//Acciones
#macro STANDARD "STANDARD"
#macro MOVE "MOVE"
#macro SWIFT "SWIFT"
#macro COUNTER "COUNTER"
#macro FREE "FREE"

// salvaciones
#macro FORTITUDE "FORTITUDE"
#macro REFLEX "REFLEX"
#macro WILL "WILL"

//HP
#macro TEMP "TEMP"
#macro MAX_TEMP "MAX_TEMP"
#macro MARKED "MARKED"
#macro CURE "CURE"
#macro DAMAGE "DAMAGE"

//Tipos de daño
#macro ACID "ACID"
#macro AXIOMATIC "AXIOMATIC"
#macro BLUDGEONING "BLUDGEONING"
#macro CHAOTIC "CHAOTIC"
#macro COLD "COLD"
#macro ELECTRIC "ELECTRIC"
#macro EVIL "EVIL"
#macro FIRE "FIRE"
#macro FORCE "FORCE"
#macro GOOD "GOOD"
#macro PIERCING "PIERCING"
#macro SLASHING "SLASHING"


//Tipos de bonificadores
#macro UNTYPED "UNTYPED"
#macro BASE "BASE"
#macro ALCHEMICAL "ALCHEMICAL"
#macro ARMOR "ARMOR"
#macro CIRCUMSTANCE "CIRCUMSTANCE"
#macro COMPETENCE "COMPETENCE"
#macro DEFLECTION "DEFLECTION"
#macro DODGE "DODGE"
#macro ENHANCEMENT "ENHANCEMENT"
#macro INSIGHT "INSIGHT"
#macro LUCK "LUCK"
#macro MORALE "MORALE"
#macro NATURAL_ARMOR "NATIRAL_ARMOR"
#macro PROFANE "PROFANE"
#macro RACIAL "RACIAL"
#macro RESISTANCE "RESISTANCE"
#macro SACRED "SACRED"
#macro SHIELD "SHIELD"
#macro SIZE "SIZE"
#macro ABILITY "ABILITY"

// Habilidades
#macro HIT_POINTS "HIT_POINTS"
#macro ARMOR_CLASS "ARMOR_CLASS"
#macro DAMAGE_REDUCTION "DAMAGE_REDUCTION"

#macro STR "STR"
#macro DEX "DEX"
#macro CON "CON"
#macro INT "INT"
#macro WIS "WIS"
#macro CHA "CHA"

#macro ACROBATICS "ACROBATICS"
#macro ALCHEMY "ALCHEMY"
#macro ARMORS "ARMORS"
#macro APPRAISE "APPRAISE"
#macro BLUFF "BLUFF"
#macro CLIMB "CLIMB"
#macro DIPLOMACY "DIPLOMACY"
#macro DISABLE_DEVICE "DISBLE_DEVICE"
#macro ESCAPE "ESCAPE"
#macro HEAL "HEAL"
#macro HEAVY_WEAPONS "HEAVY_WEAPONS"
#macro INTIMIDATE "INTIMIDATE"
#macro LIGHT_WEAPONS "LIGHT_WEAPONS"
#macro PERCEPTION "PERCEPTION"
#macro SENSE_MOTIVE "SENSE_MOTIVE"
#macro SPELLCRAFT "SPELLCRAFT"
#macro STEALTH "STEALTH"
#macro SURVIVAL "SURVIVAL"
#macro TAYLOR "TAYLOR"

//specials
#macro SASPD "SASPD"
#macro MASPD "MASPD"
#macro SWASPD "SWASPD"
#macro CASPD "CASPD"
#macro MSPEED "MSPEED"

//targets
#macro TARGET_ME "TARGET_ME"
#macro TARGET_OTHER "TARGET_OTHER"
#macro TARGET_EITHER "TARGET_EITHER"
#macro TARGET_POINTER "TARGET_POINTER"
#macro TARGET_EQUIPED "TARGET_EQUIPED"



